version: "3.7"

services:
  to-do-api:
    logging:
      driver: awslogs
      options:
        awslogs-group: log-group-to-do-app
        awslogs-create-group: "true"
        awslogs-stream: log-stream-to-do-api
