name: Build tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: [self-hosted, builder]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Build and push tagged image
        run: |
          docker image build \
            --no-cache \
            --tag alvarogarciafer/to-do-app_api:${{ steps.get-tag.outputs.TAG }} \
            .
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login \
            --username ${{ secrets.DOCKER_HUB_USERNAME }} \
            --password-stdin
          docker image push \
            alvarogarciafer/to-do-app_api:${{ steps.get-tag.outputs.TAG }}
