name: On pull request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, development]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Run linter and tests
        run: |
          docker image build --tag alvarogarciafer/to-do-api:test .
          docker container run --rm alvarogarciafer/to-do-api:test run lint
          docker container run --rm alvarogarciafer/to-do-api:test test
          docker image rm alvarogarciafer/to-do-api:test
