name: Stop

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'development'

jobs:
  stop:
    runs-on: [self-hosted, "${{ github.event.inputs.environment }}"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Stop and remove containers
        run: |
          docker container stop \
            to-do-api
          docker container rm \
            to-do-api
