name: stop

env:
  CONTAINER_NAME: 'to-do-api'

on: 
  workflow_dispatch:

jobs:
  stop:
    runs-on: self-hosted
    steps:
      - name: Stop containers
        run: |
          docker container stop ${{ env.CONTAINER_NAME}} || true
          docker container rm ${{ env.CONTAINER_NAME}} || true
