name: Stop production

on:
  workflow_dispatch:

jobs:
  stop:
    runs-on: [self-hosted, production]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Stop and remove containers
        run: |
          echo "NODE_ENV=production" >> .env
          echo "PORT=3000" >> .env
          docker-compose down
          rm .env
