name: Stop development

on:
  workflow_dispatch:

jobs:
  stop:
    runs-on: [self-hosted, development]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Stop and remove containers
        run: |
          echo "NODE_ENV=development" >> .env
          docker-compose down
          rm .env
