name: Triggered deploy

on:
  repository_dispatch:
    types: [deploy]

jobs:          
  deploy:
    runs-on: [self-hosted, "${{ github.event.client_payload.environment }}"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy containers
        env:
          NODE_ENV: production
          TAG: ${{ github.event.client_payload.tag }}
          PORT: 3000
          MONGO_HOST: mongo
          MONGO_PORT: 27017
        run: |
          docker network create \
            network-to-do-app || true
          echo ${{ secrets.PACKAGES_ACCESS_TOKEN }} | docker login \
            ghcr.io \
            --username alvarogarciafer \
            --password-stdin
          docker-compose pull
          docker-compose up \
            --detach
          docker image prune \
            --all \
            --force
